apiVersion: environmentsettings.dynatrace.crossplane.io/v1alpha1
kind: AppMonitoring
metadata:
  annotations:
    meta.upbound.io/example-id: environmentsettings/v1alpha1/appmonitoring
  labels:
    testing.upbound.io/example-name: '#name#'
  name: '#name#'
spec:
  forProvider:
    defaultLogLevel: "off"
