apiVersion: environmentsettings.dynatrace.crossplane.io/v1alpha1
kind: AuditLog
metadata:
  annotations:
    meta.upbound.io/example-id: environmentsettings/v1alpha1/auditlog
  labels:
    testing.upbound.io/example-name: '#name#'
  name: '#name#'
spec:
  forProvider:
    enabled: false
