apiVersion: notifications.dynatrace.crossplane.io/v1alpha1
kind: SlackNotification
metadata:
  annotations:
    meta.upbound.io/example-id: notifications/v1alpha1/slacknotification
  labels:
    testing.upbound.io/example-name: '#name#'
  name: '#name#'
spec:
  forProvider:
    active: false
    channel: '#name#'
    message: slack-message
    name: '#name#'
    profile: ${dynatrace_alerting.Default.id}
    urlSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system

---

apiVersion: notifications.dynatrace.crossplane.io/v1alpha1
kind: Alerting
metadata:
  annotations:
    meta.upbound.io/example-id: notifications/v1alpha1/slacknotification
  labels:
    testing.upbound.io/example-name: Default
  name: default
spec:
  forProvider:
    name: '#name#'
