apiVersion: notifications.dynatrace.crossplane.io/v1alpha1
kind: VictorOpsNotification
metadata:
  annotations:
    meta.upbound.io/example-id: notifications/v1alpha1/victoropsnotification
  labels:
    testing.upbound.io/example-name: '#name#'
  name: '#name#'
spec:
  forProvider:
    active: false
    apiKeySecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    message: victor-ops-message
    name: '#name#'
    profile: ${dynatrace_alerting.Default.id}
    routingKey: victor-ops-routing-key

---

apiVersion: notifications.dynatrace.crossplane.io/v1alpha1
kind: Alerting
metadata:
  annotations:
    meta.upbound.io/example-id: notifications/v1alpha1/victoropsnotification
  labels:
    testing.upbound.io/example-name: Default
  name: default
spec:
  forProvider:
    name: '#name#'
