// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *AlertingProfile) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ApplicationAnomalies) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Autotag) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CloudfoundryCredentials) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CustomAnomalies) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Dashboard) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DatabaseAnomalies) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DduPool) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DiskAnomalies) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *HostAnomalies) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *K8SCredentials) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MaintenanceWindow) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ManagementZone) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Notification) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PgAnomalies) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ResourceAttributes) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ServiceAnomalies) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SLO) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SpanEvents) Hub() {}
