// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type SpanEventsInitParameters struct {

	// (String) Key of the span event attribute to store
	// Key of the span event attribute to store
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String) Possible Values: MASK_ENTIRE_VALUE, MASK_ONLY_CONFIDENTIAL_DATA, NOT_MASKED
	// Possible Values: `MASK_ENTIRE_VALUE`, `MASK_ONLY_CONFIDENTIAL_DATA`, `NOT_MASKED`
	Masking *string `json:"masking,omitempty" tf:"masking,omitempty"`
}

type SpanEventsObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Key of the span event attribute to store
	// Key of the span event attribute to store
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String) Possible Values: MASK_ENTIRE_VALUE, MASK_ONLY_CONFIDENTIAL_DATA, NOT_MASKED
	// Possible Values: `MASK_ENTIRE_VALUE`, `MASK_ONLY_CONFIDENTIAL_DATA`, `NOT_MASKED`
	Masking *string `json:"masking,omitempty" tf:"masking,omitempty"`
}

type SpanEventsParameters struct {

	// (String) Key of the span event attribute to store
	// Key of the span event attribute to store
	// +kubebuilder:validation:Optional
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String) Possible Values: MASK_ENTIRE_VALUE, MASK_ONLY_CONFIDENTIAL_DATA, NOT_MASKED
	// Possible Values: `MASK_ENTIRE_VALUE`, `MASK_ONLY_CONFIDENTIAL_DATA`, `NOT_MASKED`
	// +kubebuilder:validation:Optional
	Masking *string `json:"masking,omitempty" tf:"masking,omitempty"`
}

// SpanEventsSpec defines the desired state of SpanEvents
type SpanEventsSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     SpanEventsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SpanEventsInitParameters `json:"initProvider,omitempty"`
}

// SpanEventsStatus defines the observed state of SpanEvents.
type SpanEventsStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SpanEventsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SpanEvents is the Schema for the SpanEventss API. The resource
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,dynatrace}
type SpanEvents struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.key) || (has(self.initProvider) && has(self.initProvider.key))",message="spec.forProvider.key is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.masking) || (has(self.initProvider) && has(self.initProvider.masking))",message="spec.forProvider.masking is a required parameter"
	Spec   SpanEventsSpec   `json:"spec"`
	Status SpanEventsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SpanEventsList contains a list of SpanEventss
type SpanEventsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SpanEvents `json:"items"`
}

// Repository type metadata.
var (
	SpanEvents_Kind             = "SpanEvents"
	SpanEvents_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SpanEvents_Kind}.String()
	SpanEvents_KindAPIVersion   = SpanEvents_Kind + "." + CRDGroupVersion.String()
	SpanEvents_GroupVersionKind = CRDGroupVersion.WithKind(SpanEvents_Kind)
)

func init() {
	SchemeBuilder.Register(&SpanEvents{}, &SpanEventsList{})
}
