//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevobsAgentOptin) DeepCopyInto(out *DevobsAgentOptin) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevobsAgentOptin.
func (in *DevobsAgentOptin) DeepCopy() *DevobsAgentOptin {
	if in == nil {
		return nil
	}
	out := new(DevobsAgentOptin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DevobsAgentOptin) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevobsAgentOptinInitParameters) DeepCopyInto(out *DevobsAgentOptinInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevobsAgentOptinInitParameters.
func (in *DevobsAgentOptinInitParameters) DeepCopy() *DevobsAgentOptinInitParameters {
	if in == nil {
		return nil
	}
	out := new(DevobsAgentOptinInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevobsAgentOptinList) DeepCopyInto(out *DevobsAgentOptinList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DevobsAgentOptin, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevobsAgentOptinList.
func (in *DevobsAgentOptinList) DeepCopy() *DevobsAgentOptinList {
	if in == nil {
		return nil
	}
	out := new(DevobsAgentOptinList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DevobsAgentOptinList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevobsAgentOptinObservation) DeepCopyInto(out *DevobsAgentOptinObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevobsAgentOptinObservation.
func (in *DevobsAgentOptinObservation) DeepCopy() *DevobsAgentOptinObservation {
	if in == nil {
		return nil
	}
	out := new(DevobsAgentOptinObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevobsAgentOptinParameters) DeepCopyInto(out *DevobsAgentOptinParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevobsAgentOptinParameters.
func (in *DevobsAgentOptinParameters) DeepCopy() *DevobsAgentOptinParameters {
	if in == nil {
		return nil
	}
	out := new(DevobsAgentOptinParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevobsAgentOptinSpec) DeepCopyInto(out *DevobsAgentOptinSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevobsAgentOptinSpec.
func (in *DevobsAgentOptinSpec) DeepCopy() *DevobsAgentOptinSpec {
	if in == nil {
		return nil
	}
	out := new(DevobsAgentOptinSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevobsAgentOptinStatus) DeepCopyInto(out *DevobsAgentOptinStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevobsAgentOptinStatus.
func (in *DevobsAgentOptinStatus) DeepCopy() *DevobsAgentOptinStatus {
	if in == nil {
		return nil
	}
	out := new(DevobsAgentOptinStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevobsDataMasking) DeepCopyInto(out *DevobsDataMasking) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevobsDataMasking.
func (in *DevobsDataMasking) DeepCopy() *DevobsDataMasking {
	if in == nil {
		return nil
	}
	out := new(DevobsDataMasking)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DevobsDataMasking) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevobsDataMaskingInitParameters) DeepCopyInto(out *DevobsDataMaskingInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.InsertAfter != nil {
		in, out := &in.InsertAfter, &out.InsertAfter
		*out = new(string)
		**out = **in
	}
	if in.ReplacementPattern != nil {
		in, out := &in.ReplacementPattern, &out.ReplacementPattern
		*out = new(string)
		**out = **in
	}
	if in.ReplacementType != nil {
		in, out := &in.ReplacementType, &out.ReplacementType
		*out = new(string)
		**out = **in
	}
	if in.RuleName != nil {
		in, out := &in.RuleName, &out.RuleName
		*out = new(string)
		**out = **in
	}
	if in.RuleRegex != nil {
		in, out := &in.RuleRegex, &out.RuleRegex
		*out = new(string)
		**out = **in
	}
	if in.RuleType != nil {
		in, out := &in.RuleType, &out.RuleType
		*out = new(string)
		**out = **in
	}
	if in.RuleVarName != nil {
		in, out := &in.RuleVarName, &out.RuleVarName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevobsDataMaskingInitParameters.
func (in *DevobsDataMaskingInitParameters) DeepCopy() *DevobsDataMaskingInitParameters {
	if in == nil {
		return nil
	}
	out := new(DevobsDataMaskingInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevobsDataMaskingList) DeepCopyInto(out *DevobsDataMaskingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DevobsDataMasking, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevobsDataMaskingList.
func (in *DevobsDataMaskingList) DeepCopy() *DevobsDataMaskingList {
	if in == nil {
		return nil
	}
	out := new(DevobsDataMaskingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DevobsDataMaskingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevobsDataMaskingObservation) DeepCopyInto(out *DevobsDataMaskingObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.InsertAfter != nil {
		in, out := &in.InsertAfter, &out.InsertAfter
		*out = new(string)
		**out = **in
	}
	if in.ReplacementPattern != nil {
		in, out := &in.ReplacementPattern, &out.ReplacementPattern
		*out = new(string)
		**out = **in
	}
	if in.ReplacementType != nil {
		in, out := &in.ReplacementType, &out.ReplacementType
		*out = new(string)
		**out = **in
	}
	if in.RuleName != nil {
		in, out := &in.RuleName, &out.RuleName
		*out = new(string)
		**out = **in
	}
	if in.RuleRegex != nil {
		in, out := &in.RuleRegex, &out.RuleRegex
		*out = new(string)
		**out = **in
	}
	if in.RuleType != nil {
		in, out := &in.RuleType, &out.RuleType
		*out = new(string)
		**out = **in
	}
	if in.RuleVarName != nil {
		in, out := &in.RuleVarName, &out.RuleVarName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevobsDataMaskingObservation.
func (in *DevobsDataMaskingObservation) DeepCopy() *DevobsDataMaskingObservation {
	if in == nil {
		return nil
	}
	out := new(DevobsDataMaskingObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevobsDataMaskingParameters) DeepCopyInto(out *DevobsDataMaskingParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.InsertAfter != nil {
		in, out := &in.InsertAfter, &out.InsertAfter
		*out = new(string)
		**out = **in
	}
	if in.ReplacementPattern != nil {
		in, out := &in.ReplacementPattern, &out.ReplacementPattern
		*out = new(string)
		**out = **in
	}
	if in.ReplacementType != nil {
		in, out := &in.ReplacementType, &out.ReplacementType
		*out = new(string)
		**out = **in
	}
	if in.RuleName != nil {
		in, out := &in.RuleName, &out.RuleName
		*out = new(string)
		**out = **in
	}
	if in.RuleRegex != nil {
		in, out := &in.RuleRegex, &out.RuleRegex
		*out = new(string)
		**out = **in
	}
	if in.RuleType != nil {
		in, out := &in.RuleType, &out.RuleType
		*out = new(string)
		**out = **in
	}
	if in.RuleVarName != nil {
		in, out := &in.RuleVarName, &out.RuleVarName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevobsDataMaskingParameters.
func (in *DevobsDataMaskingParameters) DeepCopy() *DevobsDataMaskingParameters {
	if in == nil {
		return nil
	}
	out := new(DevobsDataMaskingParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevobsDataMaskingSpec) DeepCopyInto(out *DevobsDataMaskingSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevobsDataMaskingSpec.
func (in *DevobsDataMaskingSpec) DeepCopy() *DevobsDataMaskingSpec {
	if in == nil {
		return nil
	}
	out := new(DevobsDataMaskingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevobsDataMaskingStatus) DeepCopyInto(out *DevobsDataMaskingStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevobsDataMaskingStatus.
func (in *DevobsDataMaskingStatus) DeepCopy() *DevobsDataMaskingStatus {
	if in == nil {
		return nil
	}
	out := new(DevobsDataMaskingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevobsGitOnprem) DeepCopyInto(out *DevobsGitOnprem) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevobsGitOnprem.
func (in *DevobsGitOnprem) DeepCopy() *DevobsGitOnprem {
	if in == nil {
		return nil
	}
	out := new(DevobsGitOnprem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DevobsGitOnprem) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevobsGitOnpremInitParameters) DeepCopyInto(out *DevobsGitOnpremInitParameters) {
	*out = *in
	if in.GitProvider != nil {
		in, out := &in.GitProvider, &out.GitProvider
		*out = new(string)
		**out = **in
	}
	if in.IncludeCredentials != nil {
		in, out := &in.IncludeCredentials, &out.IncludeCredentials
		*out = new(bool)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevobsGitOnpremInitParameters.
func (in *DevobsGitOnpremInitParameters) DeepCopy() *DevobsGitOnpremInitParameters {
	if in == nil {
		return nil
	}
	out := new(DevobsGitOnpremInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevobsGitOnpremList) DeepCopyInto(out *DevobsGitOnpremList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DevobsGitOnprem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevobsGitOnpremList.
func (in *DevobsGitOnpremList) DeepCopy() *DevobsGitOnpremList {
	if in == nil {
		return nil
	}
	out := new(DevobsGitOnpremList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DevobsGitOnpremList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevobsGitOnpremObservation) DeepCopyInto(out *DevobsGitOnpremObservation) {
	*out = *in
	if in.GitProvider != nil {
		in, out := &in.GitProvider, &out.GitProvider
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IncludeCredentials != nil {
		in, out := &in.IncludeCredentials, &out.IncludeCredentials
		*out = new(bool)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevobsGitOnpremObservation.
func (in *DevobsGitOnpremObservation) DeepCopy() *DevobsGitOnpremObservation {
	if in == nil {
		return nil
	}
	out := new(DevobsGitOnpremObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevobsGitOnpremParameters) DeepCopyInto(out *DevobsGitOnpremParameters) {
	*out = *in
	if in.GitProvider != nil {
		in, out := &in.GitProvider, &out.GitProvider
		*out = new(string)
		**out = **in
	}
	if in.IncludeCredentials != nil {
		in, out := &in.IncludeCredentials, &out.IncludeCredentials
		*out = new(bool)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevobsGitOnpremParameters.
func (in *DevobsGitOnpremParameters) DeepCopy() *DevobsGitOnpremParameters {
	if in == nil {
		return nil
	}
	out := new(DevobsGitOnpremParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevobsGitOnpremSpec) DeepCopyInto(out *DevobsGitOnpremSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevobsGitOnpremSpec.
func (in *DevobsGitOnpremSpec) DeepCopy() *DevobsGitOnpremSpec {
	if in == nil {
		return nil
	}
	out := new(DevobsGitOnpremSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevobsGitOnpremStatus) DeepCopyInto(out *DevobsGitOnpremStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevobsGitOnpremStatus.
func (in *DevobsGitOnpremStatus) DeepCopy() *DevobsGitOnpremStatus {
	if in == nil {
		return nil
	}
	out := new(DevobsGitOnpremStatus)
	in.DeepCopyInto(out)
	return out
}
