apiVersion: deprecated.dynatrace.crossplane.io/v1alpha1
kind: K8SCredentials
metadata:
  annotations:
    meta.upbound.io/example-id: deprecated/v1alpha1/k8scredentials
  labels:
    testing.upbound.io/example-name: '#name#'
  name: '#name#'
spec:
  forProvider:
    active: false
    authTokenSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    certificateCheckEnabled: false
    endpointUrl: https://${randomize}.${randomize}.com:6443/
    eventAnalysisAndAlertingEnabled: true
    eventsFieldSelectors:
    - active: true
      fieldSelector: involvedObject.kind=Node
      label: Node events
    eventsIntegrationEnabled: true
    hostnameVerification: false
    label: '#name#'
    prometheusExporters: false
    workloadIntegrationEnabled: true
