apiVersion: deprecated.dynatrace.crossplane.io/v1alpha1
kind: MaintenanceWindow
metadata:
  annotations:
    meta.upbound.io/example-id: deprecated/v1alpha1/maintenancewindow
  labels:
    testing.upbound.io/example-name: '#name#'
  name: '#name#'
spec:
  forProvider:
    name: '#name#'
    schedule:
    - end: 2021-05-11 14:41
      recurrenceType: ONCE
      start: 2021-05-11 13:41
      zoneId: Europe/Vienna
    scope:
    - matches:
      - tagCombination: AND
        tags:
        - context: CONTEXTLESS
          key: bggtedgxen
        - context: CONTEXTLESS
          key: deldel1
    suppressSynthMonExec: true
    suppression: DONT_DETECT_PROBLEMS
    type: PLANNED
