apiVersion: deprecated.dynatrace.crossplane.io/v1alpha1
kind: ServiceAnomalies
metadata:
  annotations:
    meta.upbound.io/example-id: deprecated/v1alpha1/serviceanomalies
  labels:
    testing.upbound.io/example-name: '#name#'
  name: '#name#'
spec:
  forProvider:
    failureRates:
    - auto:
      - absolute: 0
        relative: 50
    load:
    - drops:
      - minutes: 1
        percent: 50
      spikes:
      - minutes: 1
        percent: 200
    loadDrops:
    - minutes: 1
      percent: 50
    responseTimes:
    - auto:
      - load: TEN_REQUESTS_PER_MINUTE
        milliseconds: 100
        percent: 50
        slowestMilliseconds: 1000
        slowestPercent: 100
