apiVersion: businessevents.dynatrace.crossplane.io/v1alpha1
kind: BusinessEventsMetrics
metadata:
  annotations:
    meta.upbound.io/example-id: businessevents/v1alpha1/businesseventsmetrics
  labels:
    testing.upbound.io/example-name: '#name#'
  name: '#name#'
spec:
  forProvider:
    enabled: true
    key: bizevents.easyTrade.TradingVolume
    matcher: matchesValue(event.type, "com.easytrade.buy-assets")
    measure: ATTRIBUTE
    measureAttribute: trading_volume
