apiVersion: businessevents.dynatrace.crossplane.io/v1alpha1
kind: BusinessEventsProcessing
metadata:
  annotations:
    meta.upbound.io/example-id: businessevents/v1alpha1/businesseventsprocessing
  labels:
    testing.upbound.io/example-name: '#name#'
  name: '#name#'
spec:
  forProvider:
    enabled: true
    matcher: matchesValue(event.type, "com.easytrade.buy-assets")
    ruleName: '#name#'
    ruleTesting:
    - sampleEvent: |-
        ${jsonencode({
                  "id": "OR-838475",
                  "paymentType": "paypal",
                  "plannedDeliveryDate": "01.01.2021",
                  "total": 234
              })}
    script: FIELDS_ADD(trading_volume:price*amount)
    transformationFields:
    - transformationField:
      - array: false
        name: amount
        optional: false
        readonly: true
        type: DOUBLE
      - array: false
        name: price
        optional: false
        readonly: true
        type: DOUBLE
