apiVersion: opentelemetryopentracing.dynatrace.crossplane.io/v1alpha1
kind: OpentelemetryMetrics
metadata:
  annotations:
    meta.upbound.io/example-id: opentelemetryopentracing/v1alpha1/opentelemetrymetrics
  labels:
    testing.upbound.io/example-name: '#name#'
  name: '#name#'
spec:
  forProvider:
    additionalAttributes:
    - additionalAttribute:
      - attributeKey: terraform.test.add
        enabled: true
      - attributeKey: service.name
        enabled: true
      - attributeKey: host.id
        enabled: true
      - attributeKey: host.name
        enabled: true
      - attributeKey: faas.id
        enabled: true
      - attributeKey: faas.name
        enabled: true
      - attributeKey: k8s.cluster.name
        enabled: true
      - attributeKey: k8s.node.name
        enabled: true
      - attributeKey: k8s.namespace.name
        enabled: true
      - attributeKey: k8s.deployment.name
        enabled: true
      - attributeKey: k8s.statefulset.name
        enabled: true
      - attributeKey: k8s.daemonset.name
        enabled: true
      - attributeKey: k8s.job.name
        enabled: true
      - attributeKey: k8s.cronjob.name
        enabled: true
      - attributeKey: k8s.pod.uid
        enabled: true
      - attributeKey: k8s.pod.name
        enabled: true
      - attributeKey: process.executable.name
        enabled: true
      - attributeKey: dt.metrics.source
        enabled: true
      - attributeKey: dt.entity.host
        enabled: true
      - attributeKey: dt.entity.process_group_instance
        enabled: true
      - attributeKey: dt.entity.host_group
        enabled: true
      - attributeKey: dt.kubernetes.workload.kind
        enabled: true
      - attributeKey: dt.kubernetes.workload.name
        enabled: true
      - attributeKey: dt.kubernetes.cluster.id
        enabled: true
    additionalAttributesToDimensionEnabled: true
    meterNameToDimensionEnabled: true
    scope: environment
    toDropAttributes:
    - toDropAttribute:
      - attributeKey: terraform.test.drop
        enabled: true
