// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ContainerRegistryInitParameters struct {

	// (String) Typically set without protocol. Leave empty to use default configuration
	// Typically set without protocol. Leave empty to use default configuration
	ContainerRegistry *string `json:"containerRegistry,omitempty" tf:"container_registry,omitempty"`
}

type ContainerRegistryObservation struct {

	// (String) Typically set without protocol. Leave empty to use default configuration
	// Typically set without protocol. Leave empty to use default configuration
	ContainerRegistry *string `json:"containerRegistry,omitempty" tf:"container_registry,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type ContainerRegistryParameters struct {

	// (String) Typically set without protocol. Leave empty to use default configuration
	// Typically set without protocol. Leave empty to use default configuration
	// +kubebuilder:validation:Optional
	ContainerRegistry *string `json:"containerRegistry,omitempty" tf:"container_registry,omitempty"`
}

// ContainerRegistrySpec defines the desired state of ContainerRegistry
type ContainerRegistrySpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ContainerRegistryParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ContainerRegistryInitParameters `json:"initProvider,omitempty"`
}

// ContainerRegistryStatus defines the observed state of ContainerRegistry.
type ContainerRegistryStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ContainerRegistryObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ContainerRegistry is the Schema for the ContainerRegistrys API. The resource
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,dynatrace}
type ContainerRegistry struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ContainerRegistrySpec   `json:"spec"`
	Status            ContainerRegistryStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ContainerRegistryList contains a list of ContainerRegistrys
type ContainerRegistryList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ContainerRegistry `json:"items"`
}

// Repository type metadata.
var (
	ContainerRegistry_Kind             = "ContainerRegistry"
	ContainerRegistry_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ContainerRegistry_Kind}.String()
	ContainerRegistry_KindAPIVersion   = ContainerRegistry_Kind + "." + CRDGroupVersion.String()
	ContainerRegistry_GroupVersionKind = CRDGroupVersion.WithKind(ContainerRegistry_Kind)
)

func init() {
	SchemeBuilder.Register(&ContainerRegistry{}, &ContainerRegistryList{})
}
