apiVersion: iam.dynatrace.crossplane.io/v1alpha1
kind: IAMPolicyBindings
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/iampolicybindings
  labels:
    testing.upbound.io/example-name: env_bindings
  name: env-bindings
spec:
  forProvider:
    environment: siz654##
    group: ${dynatrace_iam_group.my_group.id}
    policies:
    - ${dynatrace_iam_policy.env_policy.id}

---

apiVersion: iam.dynatrace.crossplane.io/v1alpha1
kind: IAMGroup
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/iampolicybindings
  labels:
    testing.upbound.io/example-name: my_group
  name: my-group
spec:
  forProvider:
    name: my_group
    permissions:
    - {}

---

apiVersion: iam.dynatrace.crossplane.io/v1alpha1
kind: IAMPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/iampolicybindings
  labels:
    testing.upbound.io/example-name: acc_policy
  name: acc-policy
spec:
  forProvider:
    account: '########-####-####-####-############'
    name: my_policy_valid_for_all_environments_in_this_account
    statementQuery: ALLOW settings:objects:read, settings:schemas:read WHERE settings:schemaId
      = "string";

---

apiVersion: iam.dynatrace.crossplane.io/v1alpha1
kind: IAMPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/iampolicybindings
  labels:
    testing.upbound.io/example-name: env_policy
  name: env-policy
spec:
  forProvider:
    environment: siz654##
    name: my_policy_valid_for_environment_siz654##
    statementQuery: ALLOW settings:objects:read, settings:schemas:read WHERE settings:schemaId
      = "string";
