apiVersion: iam.dynatrace.crossplane.io/v1alpha1
kind: IAMPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/iampolicy
  labels:
    testing.upbound.io/example-name: policy
  name: policy
spec:
  forProvider:
    environment: siz654##
    name: my_policy_valid_for_environment_siz654##
    statementQuery: ALLOW settings:objects:read, settings:schemas:read WHERE settings:schemaId
      = "string";
