apiVersion: iam.dynatrace.crossplane.io/v1alpha1
kind: IAMUser
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/iamuser
  labels:
    testing.upbound.io/example-name: john_doe_gmail_com
  name: john-doe-gmail-com
spec:
  forProvider:
    email: john.doe@gmail.com
    groups:
    - ${data.dynatrace_iam_group.Restricted.id}
