apiVersion: iam.dynatrace.crossplane.io/v1alpha1
kind: MgmzPermission
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/mgmzpermission
  labels:
    testing.upbound.io/example-name: some-perm
  name: some-perm
spec:
  forProvider:
    environment: d85dea6a-4287-49d3-bf62-729274ba7036
    group: ${dynatrace_user_group.group-a.id}
    managementZone: "982182035185200933"
    permissions:
    - VIEWER
    - REPLAY_SESSION_DATA
