apiVersion: iam.dynatrace.crossplane.io/v1alpha1
kind: Policy
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/policy
  labels:
    testing.upbound.io/example-name: policy
  name: policy
spec:
  forProvider:
    environment: '########-####-####-####-############'
    name: my_policy_valid_for_environment_########-####-####-####-############
    statementQuery: ALLOW settings:objects:read, settings:schemas:read WHERE settings:schemaId
      = "string";
