apiVersion: iam.dynatrace.crossplane.io/v1alpha1
kind: UserGroup
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/usergroup
  labels:
    testing.upbound.io/example-name: terraform
  name: terraform
spec:
  forProvider:
    ldapGroups:
    - Anonymous
    name: Anonymous

---

apiVersion: iam.dynatrace.crossplane.io/v1alpha1
kind: Policy
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/usergroup
  labels:
    testing.upbound.io/example-name: terraform_cluster
  name: terraform-cluster
spec:
  forProvider:
    cluster: ${var.cluster}
    name: terraform_cluster
    statementQuery: ALLOW settings:objects:read, settings:schemas:read WHERE settings:schemaId
      = "terraform-cluster";

---

apiVersion: iam.dynatrace.crossplane.io/v1alpha1
kind: Policy
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/usergroup
  labels:
    testing.upbound.io/example-name: terraform_env
  name: terraform-env
spec:
  forProvider:
    environment: ${var.environment}
    name: terraform_env
    statementQuery: ALLOW environment:roles:viewer;

---

apiVersion: iam.dynatrace.crossplane.io/v1alpha1
kind: PolicyBindings
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/usergroup
  labels:
    testing.upbound.io/example-name: terraform_cluster_binding
  name: terraform-cluster-binding
spec:
  forProvider:
    cluster: ${var.cluster}
    group: ${dynatrace_user_group.terraform.id}
    policies:
    - ${dynatrace_policy.terraform_cluster.id}

---

apiVersion: iam.dynatrace.crossplane.io/v1alpha1
kind: PolicyBindings
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/usergroup
  labels:
    testing.upbound.io/example-name: terraform_env_binding
  name: terraform-env-binding
spec:
  forProvider:
    environment: ${var.environment}
    group: ${dynatrace_user_group.terraform.id}
    policies:
    - ${dynatrace_policy.terraform_env.id}

---

apiVersion: iam.dynatrace.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/usergroup
  labels:
    testing.upbound.io/example-name: terraform
  name: terraform
spec:
  forProvider:
    email: me@home.com
    firstName: John
    groups:
    - ${dynatrace_user_group.terraform.id}
    lastName: Doe
    userName: me@home.com
