apiVersion: servicedetection.dynatrace.crossplane.io/v1alpha1
kind: UnifiedServicesOpentel
metadata:
  annotations:
    meta.upbound.io/example-id: servicedetection/v1alpha1/unifiedservicesopentel
  labels:
    testing.upbound.io/example-name: '#name#'
  name: '#name#'
spec:
  forProvider:
    enabled: true
