// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Alerting) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AnsibleTowerNotification) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *EmailNotification) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *JiraNotification) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MobileNotifications) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OpsGenieNotification) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PagerDutyNotification) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ServiceNowNotification) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SlackNotification) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *TrelloNotification) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VictorOpsNotification) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *WebhookNotification) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *XmattersNotification) Hub() {}
