// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type HeaderInitParameters struct {

	// (String) The name of the notification configuration
	// The name of the HTTP header
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String, Sensitive) The value of the HTTP header as a sensitive property. May contain an empty value. secret_value and value are mutually exclusive. Only one of those two is allowed to be specified.
	// The value of the HTTP header as a sensitive property. May contain an empty value. `secret_value` and `value` are mutually exclusive. Only one of those two is allowed to be specified.
	SecretValueSecretRef *v1.SecretKeySelector `json:"secretValueSecretRef,omitempty" tf:"-"`

	// (String) The value of the HTTP header. May contain an empty value. secret_value and value are mutually exclusive. Only one of those two is allowed to be specified.
	// The value of the HTTP header. May contain an empty value. `secret_value` and `value` are mutually exclusive. Only one of those two is allowed to be specified.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type HeaderObservation struct {

	// (String) The name of the notification configuration
	// The name of the HTTP header
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The value of the HTTP header. May contain an empty value. secret_value and value are mutually exclusive. Only one of those two is allowed to be specified.
	// The value of the HTTP header. May contain an empty value. `secret_value` and `value` are mutually exclusive. Only one of those two is allowed to be specified.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type HeaderParameters struct {

	// (String) The name of the notification configuration
	// The name of the HTTP header
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// (String, Sensitive) The value of the HTTP header as a sensitive property. May contain an empty value. secret_value and value are mutually exclusive. Only one of those two is allowed to be specified.
	// The value of the HTTP header as a sensitive property. May contain an empty value. `secret_value` and `value` are mutually exclusive. Only one of those two is allowed to be specified.
	// +kubebuilder:validation:Optional
	SecretValueSecretRef *v1.SecretKeySelector `json:"secretValueSecretRef,omitempty" tf:"-"`

	// (String) The value of the HTTP header. May contain an empty value. secret_value and value are mutually exclusive. Only one of those two is allowed to be specified.
	// The value of the HTTP header. May contain an empty value. `secret_value` and `value` are mutually exclusive. Only one of those two is allowed to be specified.
	// +kubebuilder:validation:Optional
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type HeadersInitParameters struct {

	// (Block Set, Min: 1) An additional HTTP Header to include when sending requests (see below for nested schema)
	// An additional HTTP Header to include when sending requests
	Header []HeaderInitParameters `json:"header,omitempty" tf:"header,omitempty"`
}

type HeadersObservation struct {

	// (Block Set, Min: 1) An additional HTTP Header to include when sending requests (see below for nested schema)
	// An additional HTTP Header to include when sending requests
	Header []HeaderObservation `json:"header,omitempty" tf:"header,omitempty"`
}

type HeadersParameters struct {

	// (Block Set, Min: 1) An additional HTTP Header to include when sending requests (see below for nested schema)
	// An additional HTTP Header to include when sending requests
	// +kubebuilder:validation:Optional
	Header []HeaderParameters `json:"header" tf:"header,omitempty"`
}

type Oauth2CredentialsInitParameters struct {

	// (String) Access token URL
	// Access token URL
	AccessTokenURL *string `json:"accessTokenUrl,omitempty" tf:"access_token_url,omitempty"`

	// (Boolean) If false, the client credentials are included in the HTTP request body.
	// If false, the client credentials are included in the HTTP request body.
	AuthenticateViaRequestHeader *bool `json:"authenticateViaRequestHeader,omitempty" tf:"authenticate_via_request_header,omitempty"`

	// (String) Client ID
	// Client ID
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// (String, Sensitive) Client secret
	// Client secret
	ClientSecretSecretRef v1.SecretKeySelector `json:"clientSecretSecretRef" tf:"-"`

	// (String) The scope of access you are requesting
	// The scope of access you are requesting
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`
}

type Oauth2CredentialsObservation struct {

	// (String) Access token URL
	// Access token URL
	AccessTokenURL *string `json:"accessTokenUrl,omitempty" tf:"access_token_url,omitempty"`

	// (Boolean) If false, the client credentials are included in the HTTP request body.
	// If false, the client credentials are included in the HTTP request body.
	AuthenticateViaRequestHeader *bool `json:"authenticateViaRequestHeader,omitempty" tf:"authenticate_via_request_header,omitempty"`

	// (String) Client ID
	// Client ID
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// (String) The scope of access you are requesting
	// The scope of access you are requesting
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`
}

type Oauth2CredentialsParameters struct {

	// (String) Access token URL
	// Access token URL
	// +kubebuilder:validation:Optional
	AccessTokenURL *string `json:"accessTokenUrl" tf:"access_token_url,omitempty"`

	// (Boolean) If false, the client credentials are included in the HTTP request body.
	// If false, the client credentials are included in the HTTP request body.
	// +kubebuilder:validation:Optional
	AuthenticateViaRequestHeader *bool `json:"authenticateViaRequestHeader,omitempty" tf:"authenticate_via_request_header,omitempty"`

	// (String) Client ID
	// Client ID
	// +kubebuilder:validation:Optional
	ClientID *string `json:"clientId" tf:"client_id,omitempty"`

	// (String, Sensitive) Client secret
	// Client secret
	// +kubebuilder:validation:Optional
	ClientSecretSecretRef v1.SecretKeySelector `json:"clientSecretSecretRef" tf:"-"`

	// (String) The scope of access you are requesting
	// The scope of access you are requesting
	// +kubebuilder:validation:Optional
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`
}

type WebhookNotificationInitParameters struct {

	// (Boolean) The configuration is enabled (true) or disabled (false)
	// The configuration is enabled (`true`) or disabled (`false`)
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// (Block List, Max: 1) A list of the additional HTTP headers (see below for nested schema)
	// A list of the additional HTTP headers
	Headers []HeadersInitParameters `json:"headers,omitempty" tf:"headers,omitempty"`

	// signed and invalid, SSL certificate (true) or only trusted (false) certificates
	// Accept any, including self-signed and invalid, SSL certificate (`true`) or only trusted (`false`) certificates
	Insecure *bool `json:"insecure,omitempty" tf:"insecure,omitempty"`

	// (String) The ID of these settings when referred to from resources requiring the REST API V1 keys
	// The ID of these settings when referred to from resources requiring the REST API V1 keys
	LegacyID *string `json:"legacyId,omitempty" tf:"legacy_id,omitempty"`

	// (String) The name of the notification configuration
	// The name of the notification configuration
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Send email if problem is closed
	// Send email if problem is closed
	NotifyClosedProblems *bool `json:"notifyClosedProblems,omitempty" tf:"notify_closed_problems,omitempty"`

	// (Boolean) Call webhook if new events merge into existing problems
	// Call webhook if new events merge into existing problems
	NotifyEventMerges *bool `json:"notifyEventMerges,omitempty" tf:"notify_event_merges,omitempty"`

	// (Block List, Max: 1) To authenticate your integration, the OAuth 2.0 Client Credentials Flow (Grant Type) is used. For details see Client Credentials Flow).
	// To authenticate your integration, the OAuth 2.0 *Client Credentials* Flow (Grant Type) is used. For details see [Client Credentials Flow](https://dt-url.net/ym22wsm)).
	//
	// The obtained Access Token is subsequently provided in the *Authorization* header of the request carrying the notification payload.
	Oauth2Credentials []Oauth2CredentialsInitParameters `json:"oauth2Credentials,omitempty" tf:"oauth_2_credentials,omitempty"`

	// formatted string.  * {ProblemDetailsJSON}: All problem event details, including root cause, as a JSON object.  * {ProblemDetailsMarkdown}: All problem event details, including root cause, as a Markdown-formatted string.  * {ProblemDetailsText}: All problem event details, including root cause, as a text-formatted string.  * {ProblemID}: The display number of the reported problem.  * {ProblemImpact}: The impact level of the problem. Possible values are APPLICATION, SERVICE, and INFRASTRUCTURE.  * {ProblemSeverity}: The severity level of the problem. Possible values are AVAILABILITY, ERROR, PERFORMANCE, RESOURCE_CONTENTION, and CUSTOM_ALERT.  * {ProblemTitle}: A short description of the problem.  * {ProblemURL}: The URL of the problem within Dynatrace.  * {State}: The state of the problem. Possible values are OPEN and RESOLVED.  * {Tags}: The list of tags that are defined for all impacted entities, separated by commas
	// The content of the notification message. You can use the following placeholders:  * `{ImpactedEntities}`: Details about the entities impacted by the problem in form of a JSON array.  * `{ImpactedEntity}`: The entity impacted by the problem or *X* impacted entities.  * `{PID}`: The ID of the reported problem.  * `{ProblemDetailsHTML}`: All problem event details, including root cause, as an HTML-formatted string.  * `{ProblemDetailsJSON}`: All problem event details, including root cause, as a JSON object.  * `{ProblemDetailsMarkdown}`: All problem event details, including root cause, as a [Markdown-formatted](https://www.markdownguide.org/cheat-sheet/) string.  * `{ProblemDetailsText}`: All problem event details, including root cause, as a text-formatted string.  * `{ProblemID}`: The display number of the reported problem.  * `{ProblemImpact}`: The [impact level](https://www.dynatrace.com/support/help/shortlink/impact-analysis) of the problem. Possible values are `APPLICATION`, `SERVICE`, and `INFRASTRUCTURE`.  * `{ProblemSeverity}`: The [severity level](https://www.dynatrace.com/support/help/shortlink/event-types) of the problem. Possible values are `AVAILABILITY`, `ERROR`, `PERFORMANCE`, `RESOURCE_CONTENTION`, and `CUSTOM_ALERT`.  * `{ProblemTitle}`: A short description of the problem.  * `{ProblemURL}`: The URL of the problem within Dynatrace.  * `{State}`: The state of the problem. Possible values are `OPEN` and `RESOLVED`.  * `{Tags}`: The list of tags that are defined for all impacted entities, separated by commas
	Payload *string `json:"payload,omitempty" tf:"payload,omitempty"`

	// (String) The ID of the associated alerting profile
	// The ID of the associated alerting profile
	Profile *string `json:"profile,omitempty" tf:"profile,omitempty"`

	// (String, Sensitive) The secret URL of the webhook endpoint.
	// The secret URL of the webhook endpoint.
	SecretURLSecretRef *v1.SecretKeySelector `json:"secretUrlSecretRef,omitempty" tf:"-"`

	// (String) The URL of the WebHook endpoint
	// The URL of the WebHook endpoint
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// (Boolean) Secret webhook URL
	// Secret webhook URL
	URLContainsSecret *bool `json:"urlContainsSecret,omitempty" tf:"url_contains_secret,omitempty"`

	// (Boolean) Use OAuth 2.0 for authentication
	// Use OAuth 2.0 for authentication
	UseOauth2 *bool `json:"useOauth2,omitempty" tf:"use_oauth_2,omitempty"`
}

type WebhookNotificationObservation struct {

	// (Boolean) The configuration is enabled (true) or disabled (false)
	// The configuration is enabled (`true`) or disabled (`false`)
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// (Block List, Max: 1) A list of the additional HTTP headers (see below for nested schema)
	// A list of the additional HTTP headers
	Headers []HeadersObservation `json:"headers,omitempty" tf:"headers,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// signed and invalid, SSL certificate (true) or only trusted (false) certificates
	// Accept any, including self-signed and invalid, SSL certificate (`true`) or only trusted (`false`) certificates
	Insecure *bool `json:"insecure,omitempty" tf:"insecure,omitempty"`

	// (String) The ID of these settings when referred to from resources requiring the REST API V1 keys
	// The ID of these settings when referred to from resources requiring the REST API V1 keys
	LegacyID *string `json:"legacyId,omitempty" tf:"legacy_id,omitempty"`

	// (String) The name of the notification configuration
	// The name of the notification configuration
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Send email if problem is closed
	// Send email if problem is closed
	NotifyClosedProblems *bool `json:"notifyClosedProblems,omitempty" tf:"notify_closed_problems,omitempty"`

	// (Boolean) Call webhook if new events merge into existing problems
	// Call webhook if new events merge into existing problems
	NotifyEventMerges *bool `json:"notifyEventMerges,omitempty" tf:"notify_event_merges,omitempty"`

	// (Block List, Max: 1) To authenticate your integration, the OAuth 2.0 Client Credentials Flow (Grant Type) is used. For details see Client Credentials Flow).
	// To authenticate your integration, the OAuth 2.0 *Client Credentials* Flow (Grant Type) is used. For details see [Client Credentials Flow](https://dt-url.net/ym22wsm)).
	//
	// The obtained Access Token is subsequently provided in the *Authorization* header of the request carrying the notification payload.
	Oauth2Credentials []Oauth2CredentialsObservation `json:"oauth2Credentials,omitempty" tf:"oauth_2_credentials,omitempty"`

	// formatted string.  * {ProblemDetailsJSON}: All problem event details, including root cause, as a JSON object.  * {ProblemDetailsMarkdown}: All problem event details, including root cause, as a Markdown-formatted string.  * {ProblemDetailsText}: All problem event details, including root cause, as a text-formatted string.  * {ProblemID}: The display number of the reported problem.  * {ProblemImpact}: The impact level of the problem. Possible values are APPLICATION, SERVICE, and INFRASTRUCTURE.  * {ProblemSeverity}: The severity level of the problem. Possible values are AVAILABILITY, ERROR, PERFORMANCE, RESOURCE_CONTENTION, and CUSTOM_ALERT.  * {ProblemTitle}: A short description of the problem.  * {ProblemURL}: The URL of the problem within Dynatrace.  * {State}: The state of the problem. Possible values are OPEN and RESOLVED.  * {Tags}: The list of tags that are defined for all impacted entities, separated by commas
	// The content of the notification message. You can use the following placeholders:  * `{ImpactedEntities}`: Details about the entities impacted by the problem in form of a JSON array.  * `{ImpactedEntity}`: The entity impacted by the problem or *X* impacted entities.  * `{PID}`: The ID of the reported problem.  * `{ProblemDetailsHTML}`: All problem event details, including root cause, as an HTML-formatted string.  * `{ProblemDetailsJSON}`: All problem event details, including root cause, as a JSON object.  * `{ProblemDetailsMarkdown}`: All problem event details, including root cause, as a [Markdown-formatted](https://www.markdownguide.org/cheat-sheet/) string.  * `{ProblemDetailsText}`: All problem event details, including root cause, as a text-formatted string.  * `{ProblemID}`: The display number of the reported problem.  * `{ProblemImpact}`: The [impact level](https://www.dynatrace.com/support/help/shortlink/impact-analysis) of the problem. Possible values are `APPLICATION`, `SERVICE`, and `INFRASTRUCTURE`.  * `{ProblemSeverity}`: The [severity level](https://www.dynatrace.com/support/help/shortlink/event-types) of the problem. Possible values are `AVAILABILITY`, `ERROR`, `PERFORMANCE`, `RESOURCE_CONTENTION`, and `CUSTOM_ALERT`.  * `{ProblemTitle}`: A short description of the problem.  * `{ProblemURL}`: The URL of the problem within Dynatrace.  * `{State}`: The state of the problem. Possible values are `OPEN` and `RESOLVED`.  * `{Tags}`: The list of tags that are defined for all impacted entities, separated by commas
	Payload *string `json:"payload,omitempty" tf:"payload,omitempty"`

	// (String) The ID of the associated alerting profile
	// The ID of the associated alerting profile
	Profile *string `json:"profile,omitempty" tf:"profile,omitempty"`

	// (String) The URL of the WebHook endpoint
	// The URL of the WebHook endpoint
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// (Boolean) Secret webhook URL
	// Secret webhook URL
	URLContainsSecret *bool `json:"urlContainsSecret,omitempty" tf:"url_contains_secret,omitempty"`

	// (Boolean) Use OAuth 2.0 for authentication
	// Use OAuth 2.0 for authentication
	UseOauth2 *bool `json:"useOauth2,omitempty" tf:"use_oauth_2,omitempty"`
}

type WebhookNotificationParameters struct {

	// (Boolean) The configuration is enabled (true) or disabled (false)
	// The configuration is enabled (`true`) or disabled (`false`)
	// +kubebuilder:validation:Optional
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// (Block List, Max: 1) A list of the additional HTTP headers (see below for nested schema)
	// A list of the additional HTTP headers
	// +kubebuilder:validation:Optional
	Headers []HeadersParameters `json:"headers,omitempty" tf:"headers,omitempty"`

	// signed and invalid, SSL certificate (true) or only trusted (false) certificates
	// Accept any, including self-signed and invalid, SSL certificate (`true`) or only trusted (`false`) certificates
	// +kubebuilder:validation:Optional
	Insecure *bool `json:"insecure,omitempty" tf:"insecure,omitempty"`

	// (String) The ID of these settings when referred to from resources requiring the REST API V1 keys
	// The ID of these settings when referred to from resources requiring the REST API V1 keys
	// +kubebuilder:validation:Optional
	LegacyID *string `json:"legacyId,omitempty" tf:"legacy_id,omitempty"`

	// (String) The name of the notification configuration
	// The name of the notification configuration
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Send email if problem is closed
	// Send email if problem is closed
	// +kubebuilder:validation:Optional
	NotifyClosedProblems *bool `json:"notifyClosedProblems,omitempty" tf:"notify_closed_problems,omitempty"`

	// (Boolean) Call webhook if new events merge into existing problems
	// Call webhook if new events merge into existing problems
	// +kubebuilder:validation:Optional
	NotifyEventMerges *bool `json:"notifyEventMerges,omitempty" tf:"notify_event_merges,omitempty"`

	// (Block List, Max: 1) To authenticate your integration, the OAuth 2.0 Client Credentials Flow (Grant Type) is used. For details see Client Credentials Flow).
	// To authenticate your integration, the OAuth 2.0 *Client Credentials* Flow (Grant Type) is used. For details see [Client Credentials Flow](https://dt-url.net/ym22wsm)).
	//
	// The obtained Access Token is subsequently provided in the *Authorization* header of the request carrying the notification payload.
	// +kubebuilder:validation:Optional
	Oauth2Credentials []Oauth2CredentialsParameters `json:"oauth2Credentials,omitempty" tf:"oauth_2_credentials,omitempty"`

	// formatted string.  * {ProblemDetailsJSON}: All problem event details, including root cause, as a JSON object.  * {ProblemDetailsMarkdown}: All problem event details, including root cause, as a Markdown-formatted string.  * {ProblemDetailsText}: All problem event details, including root cause, as a text-formatted string.  * {ProblemID}: The display number of the reported problem.  * {ProblemImpact}: The impact level of the problem. Possible values are APPLICATION, SERVICE, and INFRASTRUCTURE.  * {ProblemSeverity}: The severity level of the problem. Possible values are AVAILABILITY, ERROR, PERFORMANCE, RESOURCE_CONTENTION, and CUSTOM_ALERT.  * {ProblemTitle}: A short description of the problem.  * {ProblemURL}: The URL of the problem within Dynatrace.  * {State}: The state of the problem. Possible values are OPEN and RESOLVED.  * {Tags}: The list of tags that are defined for all impacted entities, separated by commas
	// The content of the notification message. You can use the following placeholders:  * `{ImpactedEntities}`: Details about the entities impacted by the problem in form of a JSON array.  * `{ImpactedEntity}`: The entity impacted by the problem or *X* impacted entities.  * `{PID}`: The ID of the reported problem.  * `{ProblemDetailsHTML}`: All problem event details, including root cause, as an HTML-formatted string.  * `{ProblemDetailsJSON}`: All problem event details, including root cause, as a JSON object.  * `{ProblemDetailsMarkdown}`: All problem event details, including root cause, as a [Markdown-formatted](https://www.markdownguide.org/cheat-sheet/) string.  * `{ProblemDetailsText}`: All problem event details, including root cause, as a text-formatted string.  * `{ProblemID}`: The display number of the reported problem.  * `{ProblemImpact}`: The [impact level](https://www.dynatrace.com/support/help/shortlink/impact-analysis) of the problem. Possible values are `APPLICATION`, `SERVICE`, and `INFRASTRUCTURE`.  * `{ProblemSeverity}`: The [severity level](https://www.dynatrace.com/support/help/shortlink/event-types) of the problem. Possible values are `AVAILABILITY`, `ERROR`, `PERFORMANCE`, `RESOURCE_CONTENTION`, and `CUSTOM_ALERT`.  * `{ProblemTitle}`: A short description of the problem.  * `{ProblemURL}`: The URL of the problem within Dynatrace.  * `{State}`: The state of the problem. Possible values are `OPEN` and `RESOLVED`.  * `{Tags}`: The list of tags that are defined for all impacted entities, separated by commas
	// +kubebuilder:validation:Optional
	Payload *string `json:"payload,omitempty" tf:"payload,omitempty"`

	// (String) The ID of the associated alerting profile
	// The ID of the associated alerting profile
	// +kubebuilder:validation:Optional
	Profile *string `json:"profile,omitempty" tf:"profile,omitempty"`

	// (String, Sensitive) The secret URL of the webhook endpoint.
	// The secret URL of the webhook endpoint.
	// +kubebuilder:validation:Optional
	SecretURLSecretRef *v1.SecretKeySelector `json:"secretUrlSecretRef,omitempty" tf:"-"`

	// (String) The URL of the WebHook endpoint
	// The URL of the WebHook endpoint
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// (Boolean) Secret webhook URL
	// Secret webhook URL
	// +kubebuilder:validation:Optional
	URLContainsSecret *bool `json:"urlContainsSecret,omitempty" tf:"url_contains_secret,omitempty"`

	// (Boolean) Use OAuth 2.0 for authentication
	// Use OAuth 2.0 for authentication
	// +kubebuilder:validation:Optional
	UseOauth2 *bool `json:"useOauth2,omitempty" tf:"use_oauth_2,omitempty"`
}

// WebhookNotificationSpec defines the desired state of WebhookNotification
type WebhookNotificationSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     WebhookNotificationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider WebhookNotificationInitParameters `json:"initProvider,omitempty"`
}

// WebhookNotificationStatus defines the observed state of WebhookNotification.
type WebhookNotificationStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        WebhookNotificationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// WebhookNotification is the Schema for the WebhookNotifications API. The resource
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,dynatrace}
type WebhookNotification struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.active) || (has(self.initProvider) && has(self.initProvider.active))",message="spec.forProvider.active is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.payload) || (has(self.initProvider) && has(self.initProvider.payload))",message="spec.forProvider.payload is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.profile) || (has(self.initProvider) && has(self.initProvider.profile))",message="spec.forProvider.profile is a required parameter"
	Spec   WebhookNotificationSpec   `json:"spec"`
	Status WebhookNotificationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// WebhookNotificationList contains a list of WebhookNotifications
type WebhookNotificationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []WebhookNotification `json:"items"`
}

// Repository type metadata.
var (
	WebhookNotification_Kind             = "WebhookNotification"
	WebhookNotification_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: WebhookNotification_Kind}.String()
	WebhookNotification_KindAPIVersion   = WebhookNotification_Kind + "." + CRDGroupVersion.String()
	WebhookNotification_GroupVersionKind = CRDGroupVersion.WithKind(WebhookNotification_Kind)
)

func init() {
	SchemeBuilder.Register(&WebhookNotification{}, &WebhookNotificationList{})
}
