//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserSettings) DeepCopyInto(out *UserSettings) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserSettings.
func (in *UserSettings) DeepCopy() *UserSettings {
	if in == nil {
		return nil
	}
	out := new(UserSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UserSettings) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserSettingsInitParameters) DeepCopyInto(out *UserSettingsInitParameters) {
	*out = *in
	if in.AutoLanguage != nil {
		in, out := &in.AutoLanguage, &out.AutoLanguage
		*out = new(bool)
		**out = **in
	}
	if in.AutoRegion != nil {
		in, out := &in.AutoRegion, &out.AutoRegion
		*out = new(bool)
		**out = **in
	}
	if in.AutoTheme != nil {
		in, out := &in.AutoTheme, &out.AutoTheme
		*out = new(bool)
		**out = **in
	}
	if in.AutoTimezone != nil {
		in, out := &in.AutoTimezone, &out.AutoTimezone
		*out = new(bool)
		**out = **in
	}
	if in.Language != nil {
		in, out := &in.Language, &out.Language
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.Theme != nil {
		in, out := &in.Theme, &out.Theme
		*out = new(string)
		**out = **in
	}
	if in.Timezone != nil {
		in, out := &in.Timezone, &out.Timezone
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserSettingsInitParameters.
func (in *UserSettingsInitParameters) DeepCopy() *UserSettingsInitParameters {
	if in == nil {
		return nil
	}
	out := new(UserSettingsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserSettingsList) DeepCopyInto(out *UserSettingsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UserSettings, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserSettingsList.
func (in *UserSettingsList) DeepCopy() *UserSettingsList {
	if in == nil {
		return nil
	}
	out := new(UserSettingsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UserSettingsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserSettingsObservation) DeepCopyInto(out *UserSettingsObservation) {
	*out = *in
	if in.AutoLanguage != nil {
		in, out := &in.AutoLanguage, &out.AutoLanguage
		*out = new(bool)
		**out = **in
	}
	if in.AutoRegion != nil {
		in, out := &in.AutoRegion, &out.AutoRegion
		*out = new(bool)
		**out = **in
	}
	if in.AutoTheme != nil {
		in, out := &in.AutoTheme, &out.AutoTheme
		*out = new(bool)
		**out = **in
	}
	if in.AutoTimezone != nil {
		in, out := &in.AutoTimezone, &out.AutoTimezone
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Language != nil {
		in, out := &in.Language, &out.Language
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.Theme != nil {
		in, out := &in.Theme, &out.Theme
		*out = new(string)
		**out = **in
	}
	if in.Timezone != nil {
		in, out := &in.Timezone, &out.Timezone
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserSettingsObservation.
func (in *UserSettingsObservation) DeepCopy() *UserSettingsObservation {
	if in == nil {
		return nil
	}
	out := new(UserSettingsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserSettingsParameters) DeepCopyInto(out *UserSettingsParameters) {
	*out = *in
	if in.AutoLanguage != nil {
		in, out := &in.AutoLanguage, &out.AutoLanguage
		*out = new(bool)
		**out = **in
	}
	if in.AutoRegion != nil {
		in, out := &in.AutoRegion, &out.AutoRegion
		*out = new(bool)
		**out = **in
	}
	if in.AutoTheme != nil {
		in, out := &in.AutoTheme, &out.AutoTheme
		*out = new(bool)
		**out = **in
	}
	if in.AutoTimezone != nil {
		in, out := &in.AutoTimezone, &out.AutoTimezone
		*out = new(bool)
		**out = **in
	}
	if in.Language != nil {
		in, out := &in.Language, &out.Language
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.Theme != nil {
		in, out := &in.Theme, &out.Theme
		*out = new(string)
		**out = **in
	}
	if in.Timezone != nil {
		in, out := &in.Timezone, &out.Timezone
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserSettingsParameters.
func (in *UserSettingsParameters) DeepCopy() *UserSettingsParameters {
	if in == nil {
		return nil
	}
	out := new(UserSettingsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserSettingsSpec) DeepCopyInto(out *UserSettingsSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserSettingsSpec.
func (in *UserSettingsSpec) DeepCopy() *UserSettingsSpec {
	if in == nil {
		return nil
	}
	out := new(UserSettingsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserSettingsStatus) DeepCopyInto(out *UserSettingsStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserSettingsStatus.
func (in *UserSettingsStatus) DeepCopy() *UserSettingsStatus {
	if in == nil {
		return nil
	}
	out := new(UserSettingsStatus)
	in.DeepCopyInto(out)
	return out
}
