apiVersion: webapplications.dynatrace.crossplane.io/v1alpha1
kind: WebAppRequestErrors
metadata:
  annotations:
    meta.upbound.io/example-id: webapplications/v1alpha1/webapprequesterrors
  labels:
    testing.upbound.io/example-name: '#name#'
  name: '#name#'
spec:
  forProvider:
    errorRules:
    - errorRule:
      - captureSettings:
        - capture: false
        considerCspViolations: true
        considerFailedImages: true
        errorCodes: "400"
        filterSettings:
        - filter: ENDS_WITH
          url: hashicorp
      - captureSettings:
        - capture: true
          considerForAi: false
          impactApdex: false
        considerCspViolations: false
        considerFailedImages: false
        errorCodes: "404"
        filterSettings:
        - filter: CONTAINS
          url: terraform
      - captureSettings:
        - capture: false
        considerCspViolations: false
        considerFailedImages: false
        errorCodes: "404"
        filterSettings:
        - filter: ENDS_WITH
          url: favicon.ico
      - captureSettings:
        - capture: true
          considerForAi: true
          impactApdex: true
        considerCspViolations: false
        considerFailedImages: false
        errorCodes: "404"
        filterSettings:
        - filter: ENDS_WITH
          url: .js
      - captureSettings:
        - capture: true
          considerForAi: true
          impactApdex: true
        considerCspViolations: false
        considerFailedImages: false
        errorCodes: "404"
        filterSettings:
        - filter: ENDS_WITH
          url: .css
      - captureSettings:
        - capture: true
          considerForAi: false
          impactApdex: true
        considerCspViolations: false
        considerFailedImages: false
        errorCodes: 400-499
        filterSettings:
        - {}
      - captureSettings:
        - capture: true
          considerForAi: true
          impactApdex: true
        considerCspViolations: false
        considerFailedImages: false
        errorCodes: 500-599
        filterSettings:
        - {}
      - captureSettings:
        - capture: true
          considerForAi: false
          impactApdex: true
        considerCspViolations: false
        considerFailedImages: false
        errorCodes: 970-979
        filterSettings:
        - {}
      - captureSettings:
        - capture: true
          considerForAi: false
          impactApdex: false
        considerCspViolations: false
        considerFailedImages: true
        filterSettings:
        - {}
      - captureSettings:
        - capture: true
          considerForAi: true
          impactApdex: true
        considerCspViolations: true
        considerFailedImages: false
        filterSettings:
        - {}
    ignoreRequestErrorsInApdexCalculation: false
    scope: APPLICATION-1234567890000000
