// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AllowedOutboundConnectionsInitParameters struct {

	// (Boolean) If enabled, the Dynatrace JavaScript runtime will only be able to connect to the specified hosts.
	// If enabled, the Dynatrace JavaScript runtime will only be able to connect to the specified hosts.
	Enforced *bool `json:"enforced,omitempty" tf:"enforced,omitempty"`

	// (Set of String) The Dynatrace JavaScript runtime will only be to connect to these hosts.
	// The Dynatrace JavaScript runtime will only be to connect to these hosts.
	// +listType=set
	HostList []*string `json:"hostList,omitempty" tf:"host_list,omitempty"`
}

type AllowedOutboundConnectionsObservation struct {

	// (Boolean) If enabled, the Dynatrace JavaScript runtime will only be able to connect to the specified hosts.
	// If enabled, the Dynatrace JavaScript runtime will only be able to connect to the specified hosts.
	Enforced *bool `json:"enforced,omitempty" tf:"enforced,omitempty"`

	// (Set of String) The Dynatrace JavaScript runtime will only be to connect to these hosts.
	// The Dynatrace JavaScript runtime will only be to connect to these hosts.
	// +listType=set
	HostList []*string `json:"hostList,omitempty" tf:"host_list,omitempty"`
}

type AllowedOutboundConnectionsParameters struct {

	// (Boolean) If enabled, the Dynatrace JavaScript runtime will only be able to connect to the specified hosts.
	// If enabled, the Dynatrace JavaScript runtime will only be able to connect to the specified hosts.
	// +kubebuilder:validation:Optional
	Enforced *bool `json:"enforced" tf:"enforced,omitempty"`

	// (Set of String) The Dynatrace JavaScript runtime will only be to connect to these hosts.
	// The Dynatrace JavaScript runtime will only be to connect to these hosts.
	// +kubebuilder:validation:Optional
	// +listType=set
	HostList []*string `json:"hostList,omitempty" tf:"host_list,omitempty"`
}

type LimitOutboundConnectionsInitParameters struct {

	// (Block List, Min: 1, Max: 1) no documentation available (see below for nested schema)
	// no documentation available
	AllowedOutboundConnections []AllowedOutboundConnectionsInitParameters `json:"allowedOutboundConnections,omitempty" tf:"allowed_outbound_connections,omitempty"`
}

type LimitOutboundConnectionsObservation struct {

	// (Block List, Min: 1, Max: 1) no documentation available (see below for nested schema)
	// no documentation available
	AllowedOutboundConnections []AllowedOutboundConnectionsObservation `json:"allowedOutboundConnections,omitempty" tf:"allowed_outbound_connections,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type LimitOutboundConnectionsParameters struct {

	// (Block List, Min: 1, Max: 1) no documentation available (see below for nested schema)
	// no documentation available
	// +kubebuilder:validation:Optional
	AllowedOutboundConnections []AllowedOutboundConnectionsParameters `json:"allowedOutboundConnections,omitempty" tf:"allowed_outbound_connections,omitempty"`
}

// LimitOutboundConnectionsSpec defines the desired state of LimitOutboundConnections
type LimitOutboundConnectionsSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     LimitOutboundConnectionsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider LimitOutboundConnectionsInitParameters `json:"initProvider,omitempty"`
}

// LimitOutboundConnectionsStatus defines the observed state of LimitOutboundConnections.
type LimitOutboundConnectionsStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        LimitOutboundConnectionsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// LimitOutboundConnections is the Schema for the LimitOutboundConnectionss API. The resource
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,dynatrace}
type LimitOutboundConnections struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.allowedOutboundConnections) || (has(self.initProvider) && has(self.initProvider.allowedOutboundConnections))",message="spec.forProvider.allowedOutboundConnections is a required parameter"
	Spec   LimitOutboundConnectionsSpec   `json:"spec"`
	Status LimitOutboundConnectionsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// LimitOutboundConnectionsList contains a list of LimitOutboundConnectionss
type LimitOutboundConnectionsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []LimitOutboundConnections `json:"items"`
}

// Repository type metadata.
var (
	LimitOutboundConnections_Kind             = "LimitOutboundConnections"
	LimitOutboundConnections_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: LimitOutboundConnections_Kind}.String()
	LimitOutboundConnections_KindAPIVersion   = LimitOutboundConnections_Kind + "." + CRDGroupVersion.String()
	LimitOutboundConnections_GroupVersionKind = CRDGroupVersion.WithKind(LimitOutboundConnections_Kind)
)

func init() {
	SchemeBuilder.Register(&LimitOutboundConnections{}, &LimitOutboundConnectionsList{})
}
