// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type MonitoredTechnologiesGoInitParameters struct {

	// (Boolean) This setting is enabled (true) or disabled (false)
	// This setting is enabled (`true`) or disabled (`false`)
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Boolean) Learn more about the known limitations for Go static monitoring
	// Learn more about the [known limitations for Go static monitoring](https://www.dynatrace.com/support/help/technology-support/application-software/go/support/go-known-limitations#limitations)
	EnabledGoStaticMonitoring *bool `json:"enabledGoStaticMonitoring,omitempty" tf:"enabled_go_static_monitoring,omitempty"`

	// (String) The scope of this settings. If the settings should cover the whole environment, just don't specify any scope.
	// The scope of this settings. If the settings should cover the whole environment, just don't specify any scope.
	HostID *string `json:"hostId,omitempty" tf:"host_id,omitempty"`
}

type MonitoredTechnologiesGoObservation struct {

	// (Boolean) This setting is enabled (true) or disabled (false)
	// This setting is enabled (`true`) or disabled (`false`)
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Boolean) Learn more about the known limitations for Go static monitoring
	// Learn more about the [known limitations for Go static monitoring](https://www.dynatrace.com/support/help/technology-support/application-software/go/support/go-known-limitations#limitations)
	EnabledGoStaticMonitoring *bool `json:"enabledGoStaticMonitoring,omitempty" tf:"enabled_go_static_monitoring,omitempty"`

	// (String) The scope of this settings. If the settings should cover the whole environment, just don't specify any scope.
	// The scope of this settings. If the settings should cover the whole environment, just don't specify any scope.
	HostID *string `json:"hostId,omitempty" tf:"host_id,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type MonitoredTechnologiesGoParameters struct {

	// (Boolean) This setting is enabled (true) or disabled (false)
	// This setting is enabled (`true`) or disabled (`false`)
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Boolean) Learn more about the known limitations for Go static monitoring
	// Learn more about the [known limitations for Go static monitoring](https://www.dynatrace.com/support/help/technology-support/application-software/go/support/go-known-limitations#limitations)
	// +kubebuilder:validation:Optional
	EnabledGoStaticMonitoring *bool `json:"enabledGoStaticMonitoring,omitempty" tf:"enabled_go_static_monitoring,omitempty"`

	// (String) The scope of this settings. If the settings should cover the whole environment, just don't specify any scope.
	// The scope of this settings. If the settings should cover the whole environment, just don't specify any scope.
	// +kubebuilder:validation:Optional
	HostID *string `json:"hostId,omitempty" tf:"host_id,omitempty"`
}

// MonitoredTechnologiesGoSpec defines the desired state of MonitoredTechnologiesGo
type MonitoredTechnologiesGoSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     MonitoredTechnologiesGoParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MonitoredTechnologiesGoInitParameters `json:"initProvider,omitempty"`
}

// MonitoredTechnologiesGoStatus defines the observed state of MonitoredTechnologiesGo.
type MonitoredTechnologiesGoStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        MonitoredTechnologiesGoObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// MonitoredTechnologiesGo is the Schema for the MonitoredTechnologiesGos API. The resource
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,dynatrace}
type MonitoredTechnologiesGo struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.enabled) || (has(self.initProvider) && has(self.initProvider.enabled))",message="spec.forProvider.enabled is a required parameter"
	Spec   MonitoredTechnologiesGoSpec   `json:"spec"`
	Status MonitoredTechnologiesGoStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MonitoredTechnologiesGoList contains a list of MonitoredTechnologiesGos
type MonitoredTechnologiesGoList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MonitoredTechnologiesGo `json:"items"`
}

// Repository type metadata.
var (
	MonitoredTechnologiesGo_Kind             = "MonitoredTechnologiesGo"
	MonitoredTechnologiesGo_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: MonitoredTechnologiesGo_Kind}.String()
	MonitoredTechnologiesGo_KindAPIVersion   = MonitoredTechnologiesGo_Kind + "." + CRDGroupVersion.String()
	MonitoredTechnologiesGo_GroupVersionKind = CRDGroupVersion.WithKind(MonitoredTechnologiesGo_Kind)
)

func init() {
	SchemeBuilder.Register(&MonitoredTechnologiesGo{}, &MonitoredTechnologiesGoList{})
}
