// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type MonitoredTechnologiesNginxInitParameters struct {

	// (Boolean) This setting is enabled (true) or disabled (false)
	// This setting is enabled (`true`) or disabled (`false`)
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) The scope of this settings. If the settings should cover the whole environment, just don't specify any scope.
	// The scope of this settings. If the settings should cover the whole environment, just don't specify any scope.
	HostID *string `json:"hostId,omitempty" tf:"host_id,omitempty"`
}

type MonitoredTechnologiesNginxObservation struct {

	// (Boolean) This setting is enabled (true) or disabled (false)
	// This setting is enabled (`true`) or disabled (`false`)
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) The scope of this settings. If the settings should cover the whole environment, just don't specify any scope.
	// The scope of this settings. If the settings should cover the whole environment, just don't specify any scope.
	HostID *string `json:"hostId,omitempty" tf:"host_id,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type MonitoredTechnologiesNginxParameters struct {

	// (Boolean) This setting is enabled (true) or disabled (false)
	// This setting is enabled (`true`) or disabled (`false`)
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) The scope of this settings. If the settings should cover the whole environment, just don't specify any scope.
	// The scope of this settings. If the settings should cover the whole environment, just don't specify any scope.
	// +kubebuilder:validation:Optional
	HostID *string `json:"hostId,omitempty" tf:"host_id,omitempty"`
}

// MonitoredTechnologiesNginxSpec defines the desired state of MonitoredTechnologiesNginx
type MonitoredTechnologiesNginxSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     MonitoredTechnologiesNginxParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MonitoredTechnologiesNginxInitParameters `json:"initProvider,omitempty"`
}

// MonitoredTechnologiesNginxStatus defines the observed state of MonitoredTechnologiesNginx.
type MonitoredTechnologiesNginxStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        MonitoredTechnologiesNginxObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// MonitoredTechnologiesNginx is the Schema for the MonitoredTechnologiesNginxs API. The resource
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,dynatrace}
type MonitoredTechnologiesNginx struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.enabled) || (has(self.initProvider) && has(self.initProvider.enabled))",message="spec.forProvider.enabled is a required parameter"
	Spec   MonitoredTechnologiesNginxSpec   `json:"spec"`
	Status MonitoredTechnologiesNginxStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MonitoredTechnologiesNginxList contains a list of MonitoredTechnologiesNginxs
type MonitoredTechnologiesNginxList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MonitoredTechnologiesNginx `json:"items"`
}

// Repository type metadata.
var (
	MonitoredTechnologiesNginx_Kind             = "MonitoredTechnologiesNginx"
	MonitoredTechnologiesNginx_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: MonitoredTechnologiesNginx_Kind}.String()
	MonitoredTechnologiesNginx_KindAPIVersion   = MonitoredTechnologiesNginx_Kind + "." + CRDGroupVersion.String()
	MonitoredTechnologiesNginx_GroupVersionKind = CRDGroupVersion.WithKind(MonitoredTechnologiesNginx_Kind)
)

func init() {
	SchemeBuilder.Register(&MonitoredTechnologiesNginx{}, &MonitoredTechnologiesNginxList{})
}
