// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type CrashdumpAnalyticsInitParameters struct {

	// (Boolean) Disable the feature to stop receiving information about crash details and potential problems. We recommend keeping the feature enabled.
	// Disable the feature to stop receiving information about crash details and potential problems. We recommend keeping the feature enabled.
	EnableCrashDumpAnalytics *bool `json:"enableCrashDumpAnalytics,omitempty" tf:"enable_crash_dump_analytics,omitempty"`

	// (String) The scope of this setting (HOST HOST_GROUP environment)
	// The scope of this setting (HOST HOST_GROUP environment)
	HostID *string `json:"hostId,omitempty" tf:"host_id,omitempty"`
}

type CrashdumpAnalyticsObservation struct {

	// (Boolean) Disable the feature to stop receiving information about crash details and potential problems. We recommend keeping the feature enabled.
	// Disable the feature to stop receiving information about crash details and potential problems. We recommend keeping the feature enabled.
	EnableCrashDumpAnalytics *bool `json:"enableCrashDumpAnalytics,omitempty" tf:"enable_crash_dump_analytics,omitempty"`

	// (String) The scope of this setting (HOST HOST_GROUP environment)
	// The scope of this setting (HOST HOST_GROUP environment)
	HostID *string `json:"hostId,omitempty" tf:"host_id,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type CrashdumpAnalyticsParameters struct {

	// (Boolean) Disable the feature to stop receiving information about crash details and potential problems. We recommend keeping the feature enabled.
	// Disable the feature to stop receiving information about crash details and potential problems. We recommend keeping the feature enabled.
	// +kubebuilder:validation:Optional
	EnableCrashDumpAnalytics *bool `json:"enableCrashDumpAnalytics,omitempty" tf:"enable_crash_dump_analytics,omitempty"`

	// (String) The scope of this setting (HOST HOST_GROUP environment)
	// The scope of this setting (HOST HOST_GROUP environment)
	// +kubebuilder:validation:Optional
	HostID *string `json:"hostId,omitempty" tf:"host_id,omitempty"`
}

// CrashdumpAnalyticsSpec defines the desired state of CrashdumpAnalytics
type CrashdumpAnalyticsSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     CrashdumpAnalyticsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CrashdumpAnalyticsInitParameters `json:"initProvider,omitempty"`
}

// CrashdumpAnalyticsStatus defines the observed state of CrashdumpAnalytics.
type CrashdumpAnalyticsStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CrashdumpAnalyticsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// CrashdumpAnalytics is the Schema for the CrashdumpAnalyticss API. The resource
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,dynatrace}
type CrashdumpAnalytics struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.enableCrashDumpAnalytics) || (has(self.initProvider) && has(self.initProvider.enableCrashDumpAnalytics))",message="spec.forProvider.enableCrashDumpAnalytics is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.hostId) || (has(self.initProvider) && has(self.initProvider.hostId))",message="spec.forProvider.hostId is a required parameter"
	Spec   CrashdumpAnalyticsSpec   `json:"spec"`
	Status CrashdumpAnalyticsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CrashdumpAnalyticsList contains a list of CrashdumpAnalyticss
type CrashdumpAnalyticsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CrashdumpAnalytics `json:"items"`
}

// Repository type metadata.
var (
	CrashdumpAnalytics_Kind             = "CrashdumpAnalytics"
	CrashdumpAnalytics_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: CrashdumpAnalytics_Kind}.String()
	CrashdumpAnalytics_KindAPIVersion   = CrashdumpAnalytics_Kind + "." + CRDGroupVersion.String()
	CrashdumpAnalytics_GroupVersionKind = CRDGroupVersion.WithKind(CrashdumpAnalytics_Kind)
)

func init() {
	SchemeBuilder.Register(&CrashdumpAnalytics{}, &CrashdumpAnalyticsList{})
}
