// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *AixExtension) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CrashdumpAnalytics) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DiskAnalytics) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *EbpfServiceDiscovery) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *HostMonitoring) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *HostMonitoringAdvanced) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *HostMonitoringMode) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *HostProcessGroupMonitoring) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Nettracer) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NetworkTraffic) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OsServices) Hub() {}
