apiVersion: servicemonitoring.dynatrace.crossplane.io/v1alpha1
kind: RequestAttribute
metadata:
  annotations:
    meta.upbound.io/example-id: servicemonitoring/v1alpha1/requestattribute
  labels:
    testing.upbound.io/example-name: '#name#'
  name: '#name#'
spec:
  forProvider:
    aggregation: FIRST
    confidential: false
    dataSources:
    - enabled: true
      methods:
      - capture: CLASS_NAME
        method:
        - argumentTypes:
          - '!0'
          - System.Func`2<!0,System.Threading.Tasks.Task>
          className: NServiceBus.Pipeline.Behavior`1
          methodName: Invoke
          returnType: System.Threading.Tasks.Task
          visibility: PUBLIC
      source: METHOD_PARAM
      technology: DOTNET
      valueProcessing:
      - extractSubstring:
        - delimiter: h
          position: BEFORE
        splitAt: t
        trim: true
        valueCondition:
        - negate: false
          operator: ENDS_WITH
          value: gh
        valueExtractorRegex: s(.*+)
    - enabled: true
      methods:
      - capture: CLASS_NAME
        method:
        - argumentTypes:
          - '!0'
          - System.Func`1<System.Threading.Tasks.Task>
          className: NServiceBus.Pipeline.Behavior`1
          methodName: Invoke
          returnType: System.Threading.Tasks.Task
          visibility: PUBLIC
      source: METHOD_PARAM
      technology: DOTNET
      valueProcessing:
      - splitAt: t
        trim: true
        valueCondition:
        - operator: ENDS_WITH
          value: gh
        valueExtractorRegex: s(.*+)
    - enabled: false
      methods:
      - capture: CLASS_NAME
        method:
        - argumentTypes:
          - '!0'
          - System.Func`1<System.Threading.Tasks.Task>
          className: NServiceBus.Pipeline.Behavior`1
          methodName: Invoke
          returnType: System.Threading.Tasks.Task
          visibility: PUBLIC
      source: METHOD_PARAM
      technology: DOTNET
    dataType: STRING
    enabled: true
    name: '#name#'
    normalization: ORIGINAL
    skipPersonalDataMasking: false
