apiVersion: networkavailabilitymonitors.dynatrace.crossplane.io/v1alpha1
kind: NetworkMonitor
metadata:
  annotations:
    meta.upbound.io/example-id: networkavailabilitymonitors/v1alpha1/networkmonitor
  labels:
    testing.upbound.io/example-name: DNS_Test
  name: dns-test
spec:
  forProvider:
    description: This is an example DNS test
    enabled: false
    frequencyMin: 15
    locations:
    - SYNTHETIC_LOCATION-39F97465BE7BF644
    name: DNS Test
    outageHandling:
    - globalConsecutiveOutageCountThreshold: 1
      globalOutages: true
    performanceThresholds:
    - enabled: true
      thresholds:
      - threshold:
        - aggregation: AVG
          dealertingSamples: 5
          samples: 5
          stepIndex: 0
          threshold: 100
          violatingSamples: 3
    steps:
    - step:
      - constraints:
        - constraint:
          - properties:
              operator: '>='
              value: "90"
            type: SUCCESS_RATE_PERCENT
        name: DNS Test
        properties:
          DNS_RECORD_TYPES: A
          EXECUTION_TIMEOUT: PT2S
        requestConfigurations:
        - requestConfiguration:
          - constraints:
            - constraint:
              - properties:
                  operator: =
                  statusCode: "0"
                type: DNS_STATUS_CODE
        requestType: DNS
        targetList:
        - google.com
        - yahoo.com
    tags:
    - tag:
      - context: CONTEXTLESS
        key: Key1
        source: USER
        value: Value1
    type: MULTI_PROTOCOL
