apiVersion: anomalydetection.dynatrace.crossplane.io/v1alpha1
kind: K8SPvcAnomalies
metadata:
  annotations:
    meta.upbound.io/example-id: anomalydetection/v1alpha1/k8spvcanomalies
  labels:
    testing.upbound.io/example-name: '#name#'
  name: '#name#'
spec:
  forProvider:
    lowDiskSpaceCritical:
    - configuration:
      - observationPeriodInMinutes: 5
        samplePeriodInMinutes: 3
        threshold: 100
      enabled: true
    lowDiskSpaceCriticalPercentage:
    - configuration:
      - observationPeriodInMinutes: 5
        samplePeriodInMinutes: 3
        threshold: 10
      enabled: true
    scope: environment
