apiVersion: anomalydetection.dynatrace.crossplane.io/v1alpha1
kind: MobileAppAnomalies
metadata:
  annotations:
    meta.upbound.io/example-id: anomalydetection/v1alpha1/mobileappanomalies
  labels:
    testing.upbound.io/example-name: '#name#'
  name: '#name#'
spec:
  forProvider:
    errorRateIncrease:
    - detectionMode: fixed
      enabled: true
      errorRateIncreaseFixed:
      - sensitivity: medium
        thresholdAbsolute: 6
    scope: MOBILE_APPLICATION-1234567890000000
    slowUserActions:
    - detectionMode: fixed
      enabled: true
      slowUserActionsFixed:
      - durationAvoidOveralerting:
        - minActionRate: 12
        durationThresholdAllFixed:
        - durationThreshold: 200
        durationThresholdSlowest:
        - durationThreshold: 900
        sensitivity: high
    unexpectedHighLoad:
    - enabled: true
      thresholdPercentage: 300
    unexpectedLowLoad:
    - enabled: false
