apiVersion: anomalydetection.dynatrace.crossplane.io/v1alpha1
kind: VmwareAnomalies
metadata:
  annotations:
    meta.upbound.io/example-id: anomalydetection/v1alpha1/vmwareanomalies
  labels:
    testing.upbound.io/example-name: '#name#'
  name: '#name#'
spec:
  forProvider:
    droppedPacketsDetection:
    - customThresholds:
      - droppedPacketsPerSecond: 4
      detectionMode: custom
      enabled: true
    esxiHighCpuDetection:
    - enabled: false
    esxiHighMemoryDetection:
    - customThresholds:
      - compressionDecompressionRate: 104
      detectionMode: custom
      enabled: true
    guestCpuLimitDetection:
    - customThresholds:
      - hostCpuUsagePercentage: 74
        vmCpuReadyPercentage: 13
        vmCpuUsagePercentage: 94
      detectionMode: custom
      enabled: true
    lowDatastoreSpaceDetection:
    - enabled: false
    overloadedStorageDetection:
    - customThresholds:
      - commandAbortsNumber: 4
      detectionMode: custom
      enabled: true
    slowPhysicalStorageDetection:
    - customThresholds:
      - avgReadWriteLatency: 204
        peakReadWriteLatency: 304
      detectionMode: custom
      enabled: true
    undersizedStorageDetection:
    - enabled: false
