apiVersion: realusermonitoring.dynatrace.crossplane.io/v1alpha1
kind: UserActionMetrics
metadata:
  annotations:
    meta.upbound.io/example-id: realusermonitoring/v1alpha1/useractionmetrics
  labels:
    testing.upbound.io/example-name: '#name#'
  name: '#name#'
spec:
  forProvider:
    dimensions:
    - application
    enabled: true
    filters:
    - filter:
      - fieldName: type
        operator: EQUALS
        value: Xhr
    metricKey: uacm.TerraformTest
    value:
    - type: COUNTER
