apiVersion: updates.dynatrace.crossplane.io/v1alpha1
kind: ActivegateUpdates
metadata:
  annotations:
    meta.upbound.io/example-id: updates/v1alpha1/activegateupdates
  labels:
    testing.upbound.io/example-name: '#name#'
  name: '#name#'
spec:
  forProvider:
    autoUpdate: true
    scope: environment
