apiVersion: credentials.dynatrace.crossplane.io/v1alpha1
kind: AwsCredentials
metadata:
  annotations:
    meta.upbound.io/example-id: credentials/v1alpha1/awscredentials
  labels:
    testing.upbound.io/example-name: '#name#'
  name: '#name#'
spec:
  forProvider:
    authenticationData:
    - accountId: "246186168471"
      iamRole: Dynatrace_monitoring_role_demo1
    label: '#name#'
    partitionType: AWS_DEFAULT
    taggedOnly: false
