apiVersion: credentials.dynatrace.crossplane.io/v1alpha1
kind: AwsService
metadata:
  annotations:
    meta.upbound.io/example-id: credentials/v1alpha1/awsservice
  labels:
    testing.upbound.io/example-name: TERRAFORM_SAMPLE_services
  name: terraform-sample-services
spec:
  forProvider:
    credentialsId: ${dynatrace_aws_credentials.TERRAFORM_SAMPLE.id}
    for_each: ${data.dynatrace_aws_supported_services.supported_services.services}
    name: ${each.key}
    useRecommendedMetrics: true

---

apiVersion: credentials.dynatrace.crossplane.io/v1alpha1
kind: AwsCredentials
metadata:
  annotations:
    meta.upbound.io/example-id: credentials/v1alpha1/awsservice
  labels:
    testing.upbound.io/example-name: TERRAFORM_SAMPLE
  name: terraform-sample
spec:
  forProvider:
    authenticationData:
    - accountId: "246186168471"
      iamRole: Dynatrace_monitoring_role_demo1
    label: TERRAFORM-TEST-001
    partitionType: AWS_DEFAULT
    removeDefaults: true
    taggedOnly: false
