apiVersion: credentials.dynatrace.crossplane.io/v1alpha1
kind: AzureCredentials
metadata:
  annotations:
    meta.upbound.io/example-id: credentials/v1alpha1/azurecredentials
  labels:
    testing.upbound.io/example-name: '#name#'
  name: '#name#'
spec:
  forProvider:
    active: false
    appId: ABCDE
    autoTagging: true
    directoryId: ABCDE
    keySecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    label: '#name#'
    monitorOnlyTagPairs:
    - name: string
      value: string
    monitorOnlyTaggedEntities: true
    removeDefaults: true
