apiVersion: credentials.dynatrace.crossplane.io/v1alpha1
kind: AzureService
metadata:
  annotations:
    meta.upbound.io/example-id: credentials/v1alpha1/azureservice
  labels:
    testing.upbound.io/example-name: TERRAFORM_SAMPLE_services
  name: terraform-sample-services
spec:
  forProvider:
    credentialsId: ${dynatrace_azure_credentials.TERRAFORM_SAMPLE.id}
    for_each: ${data.dynatrace_azure_supported_services.supported_services.services}
    name: ${each.key}
    useRecommendedMetrics: true

---

apiVersion: credentials.dynatrace.crossplane.io/v1alpha1
kind: AzureCredentials
metadata:
  annotations:
    meta.upbound.io/example-id: credentials/v1alpha1/azureservice
  labels:
    testing.upbound.io/example-name: TERRAFORM_SAMPLE
  name: terraform-sample
spec:
  forProvider:
    active: false
    appId: ABCDE
    autoTagging: true
    directoryId: ABCDE
    keySecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    label: TERRAFORM_SAMPLE
    monitorOnlyTagPairs:
    - name: string
      value: string
    monitorOnlyTaggedEntities: true
