apiVersion: accesstokens.dynatrace.crossplane.io/v1alpha1
kind: APIToken
metadata:
  annotations:
    meta.upbound.io/example-id: accesstokens/v1alpha1/apitoken
  labels:
    testing.upbound.io/example-name: '#name#'
  name: '#name#'
spec:
  forProvider:
    enabled: false
    name: '#name#'
    scopes:
    - geographicRegions.read
