// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type RumOverloadPreventionInitParameters struct {

	// (Number) Once this limit is reached, Dynatrace throttles the number of captured user sessions.
	// Once this limit is reached, Dynatrace [throttles the number of captured user sessions](https://dt-url.net/fm3v0p7g).
	OverloadPreventionLimit *float64 `json:"overloadPreventionLimit,omitempty" tf:"overload_prevention_limit,omitempty"`
}

type RumOverloadPreventionObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Number) Once this limit is reached, Dynatrace throttles the number of captured user sessions.
	// Once this limit is reached, Dynatrace [throttles the number of captured user sessions](https://dt-url.net/fm3v0p7g).
	OverloadPreventionLimit *float64 `json:"overloadPreventionLimit,omitempty" tf:"overload_prevention_limit,omitempty"`
}

type RumOverloadPreventionParameters struct {

	// (Number) Once this limit is reached, Dynatrace throttles the number of captured user sessions.
	// Once this limit is reached, Dynatrace [throttles the number of captured user sessions](https://dt-url.net/fm3v0p7g).
	// +kubebuilder:validation:Optional
	OverloadPreventionLimit *float64 `json:"overloadPreventionLimit,omitempty" tf:"overload_prevention_limit,omitempty"`
}

// RumOverloadPreventionSpec defines the desired state of RumOverloadPrevention
type RumOverloadPreventionSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     RumOverloadPreventionParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RumOverloadPreventionInitParameters `json:"initProvider,omitempty"`
}

// RumOverloadPreventionStatus defines the observed state of RumOverloadPrevention.
type RumOverloadPreventionStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RumOverloadPreventionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RumOverloadPrevention is the Schema for the RumOverloadPreventions API. The resource
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,dynatrace}
type RumOverloadPrevention struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.overloadPreventionLimit) || (has(self.initProvider) && has(self.initProvider.overloadPreventionLimit))",message="spec.forProvider.overloadPreventionLimit is a required parameter"
	Spec   RumOverloadPreventionSpec   `json:"spec"`
	Status RumOverloadPreventionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RumOverloadPreventionList contains a list of RumOverloadPreventions
type RumOverloadPreventionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RumOverloadPrevention `json:"items"`
}

// Repository type metadata.
var (
	RumOverloadPrevention_Kind             = "RumOverloadPrevention"
	RumOverloadPrevention_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RumOverloadPrevention_Kind}.String()
	RumOverloadPrevention_KindAPIVersion   = RumOverloadPrevention_Kind + "." + CRDGroupVersion.String()
	RumOverloadPrevention_GroupVersionKind = CRDGroupVersion.WithKind(RumOverloadPrevention_Kind)
)

func init() {
	SchemeBuilder.Register(&RumOverloadPrevention{}, &RumOverloadPreventionList{})
}
